// <auto-generated>
//   由 tools/gen-design-tokens.mjs 从 data/design-tokens.json 生成，请勿手改。
//   V9 §19.1 C2：设计 Token 直接落为 C# 静态类，设计与代码一一对应。
//   重新生成：node tools/gen-design-tokens.mjs    CI 校验：--check
//   来源 token 顶层分组：meta / color / font / spacing / radius / layers / motion / touch / accessibility
//   生成覆盖：颜色 12 个 · 数值 28 个（递归全量，非后缀筛选取样）
// </auto-generated>

namespace Whisper.Core
{
    public static class DesignTokens
    {
        // ── 颜色 ──
        /// <summary>paper = #F0E6D2</summary>
        public const string ColorPaper = "#F0E6D2";
        /// <summary>ink = #1A1A1A</summary>
        public const string ColorInk = "#1A1A1A";
        /// <summary>blood = #8B1E1E</summary>
        public const string ColorBlood = "#8B1E1E";
        /// <summary>mold = #5C8C6E</summary>
        public const string ColorMold = "#5C8C6E";
        /// <summary>bone = #D8CFBB</summary>
        public const string ColorBone = "#D8CFBB";
        /// <summary>soot = #0E0D0C</summary>
        public const string ColorSoot = "#0E0D0C";
        /// <summary>rust = #6E4A2F</summary>
        public const string ColorRust = "#6E4A2F";
        /// <summary>signal = #C9A227</summary>
        public const string ColorSignal = "#C9A227";
        /// <summary>danger = #C0392B</summary>
        public const string ColorDanger = "#C0392B";
        /// <summary>safe = #4E7A5A</summary>
        public const string ColorSafe = "#4E7A5A";
        /// <summary>hud = rgba(240,230,210,0.86)</summary>
        public const string ColorHud = "rgba(240,230,210,0.86)";
        /// <summary>hudDim = rgba(240,230,210,0.42)</summary>
        public const string ColorHudDim = "rgba(240,230,210,0.42)";

        // ── 数值（尺寸 / 时长 / 半径 / 间距 / 层级读数等，递归全量）──
        /// <summary>token 路径 font_title_sizePx = 30</summary>
        public const float FontTitleSizePx = 30f;
        /// <summary>token 路径 font_title_weight = 700</summary>
        public const float FontTitleWeight = 700f;
        /// <summary>token 路径 font_hud_sizePx = 15</summary>
        public const float FontHudSizePx = 15f;
        /// <summary>token 路径 font_hud_weight = 600</summary>
        public const float FontHudWeight = 600f;
        /// <summary>token 路径 font_body_sizePx = 14</summary>
        public const float FontBodySizePx = 14f;
        /// <summary>token 路径 font_body_weight = 400</summary>
        public const float FontBodyWeight = 400f;
        /// <summary>token 路径 font_diegetic_sizePx = 13</summary>
        public const float FontDiegeticSizePx = 13f;
        /// <summary>token 路径 font_diegetic_weight = 400</summary>
        public const float FontDiegeticWeight = 400f;
        /// <summary>token 路径 spacing_xs = 4</summary>
        public const float SpacingXs = 4f;
        /// <summary>token 路径 spacing_sm = 8</summary>
        public const float SpacingSm = 8f;
        /// <summary>token 路径 spacing_md = 16</summary>
        public const float SpacingMd = 16f;
        /// <summary>token 路径 spacing_lg = 24</summary>
        public const float SpacingLg = 24f;
        /// <summary>token 路径 spacing_xl = 40</summary>
        public const float SpacingXl = 40f;
        /// <summary>token 路径 radius_none = 0</summary>
        public const float RadiusNone = 0f;
        /// <summary>token 路径 radius_sm = 2</summary>
        public const float RadiusSm = 2f;
        /// <summary>token 路径 radius_md = 4</summary>
        public const float RadiusMd = 4f;
        /// <summary>token 路径 layers_L0_fatal_readSeconds = 0.1</summary>
        public const float LayersL0FatalReadSeconds = 0.1f;
        /// <summary>token 路径 layers_L1_tactical_readSeconds = 0.5</summary>
        public const float LayersL1TacticalReadSeconds = 0.5f;
        /// <summary>token 路径 motion_uiFadeMs = 180</summary>
        public const float MotionUiFadeMs = 180f;
        /// <summary>token 路径 motion_hudPulseMs = 900</summary>
        public const float MotionHudPulseMs = 900f;
        /// <summary>token 路径 motion_damageFlashMs = 220</summary>
        public const float MotionDamageFlashMs = 220f;
        /// <summary>token 路径 motion_blackoutFadeMs = 600</summary>
        public const float MotionBlackoutFadeMs = 600f;
        /// <summary>token 路径 motion_monsterStingerMs = 1400</summary>
        public const float MotionMonsterStingerMs = 1400f;
        /// <summary>token 路径 touch_minHitTargetPx = 44</summary>
        public const float TouchMinHitTargetPx = 44f;
        /// <summary>token 路径 touch_lookSensitivityDefault = 0.0032</summary>
        public const float TouchLookSensitivityDefault = 0.0032f;
        /// <summary>token 路径 touch_deadZonePx = 8</summary>
        public const float TouchDeadZonePx = 8f;
        /// <summary>token 路径 touch_stickRadiusPx = 68</summary>
        public const float TouchStickRadiusPx = 68f;
        /// <summary>token 路径 accessibility_contrastMinRatio = 4.5</summary>
        public const float AccessibilityContrastMinRatio = 4.5f;

        /// <summary>运行时真源（Unity 工程内路径，运行时可直接读）。</summary>
        public const string SourcePath = "Assets/Data/design-tokens.json";
    }
}
