#!/usr/bin/env node
/**
 * cs-lint.mjs — C# 静态一致性检查（本机无法编译 C# 时的最接近替代）
 *
 * 能查：括号/引号配平、namespace 闭合、interface 成员分号（含单成员接口）、
 *       using↔asmdef 引用自洽（含与其它语句同行）、资源路径存在、生成物标记、gameplay 数值常量提示
 * 不能查：类型正确性、方法重载解析、API 存在性、泛型约束、完整编译错误全集
 *
 * 踩过的坑（写在实现里避免重犯）：
 *   1. 多趟正则互相污染：`case '{':` 的 `': '` 被"字符字面量"正则吃掉，连带吞掉 `'{'` → 一次左到右扫描
 *   2. interface 成员不能按行查：单成员接口的 `}` 与成员同行会漏判 → 逐字符 + 大括号深度
 *   3. using 不能要求行首：`namespace X { using Y; }` 同行写法会漏检 → 用分隔符前缀匹配
 *
 * 用法：node tools/cs-lint.mjs
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const UNITY = path.join(ROOT, 'unity');
const SCRIPTS = path.join(UNITY, 'Assets/Scripts');

const problems = [];
const notes = [];
const P = (m) => problems.push(m);

function strip(src) {
  let out = '';
  let i = 0;
  const n = src.length;
  while (i < n) {
    const c = src[i];
    const d = src[i + 1];
    if (c === '/' && d === '/') { while (i < n && src[i] !== '\n') i++; continue; }
    if (c === '/' && d === '*') { i += 2; while (i < n && !(src[i] === '*' && src[i + 1] === '/')) i++; i += 2; continue; }
    if ((c === '@' || c === '$') && d === '"') {
      const verbatim = c === '@';
      i += 2;
      while (i < n) {
        if (verbatim && src[i] === '"' && src[i + 1] === '"') { i += 2; continue; }
        if (!verbatim && src[i] === '\\') { i += 2; continue; }
        if (src[i] === '"') { i++; break; }
        i++;
      }
      out += '""';
      continue;
    }
    if (c === '"') { i++; while (i < n && src[i] !== '"') { if (src[i] === '\\') { i += 2; continue; } i++; } i++; out += '""'; continue; }
    if (c === "'") { i++; while (i < n && src[i] !== "'") { if (src[i] === '\\') { i += 2; continue; } i++; } i++; out += "''"; continue; }
    out += c;
    i++;
  }
  return out;
}

function usingsOf(s) {
  const out = [];
  for (const m of s.matchAll(/(?:^|[;{}\s])using\s+(?:static\s+)?([A-Za-z_][\w.]*)\s*;/g)) out.push(m[1]);
  return out;
}

function interfaceIssues(s) {
  const issues = [];
  const re = /\binterface\s+([A-Za-z_]\w*)\s*(?::[^{]*)?\{/g;
  let m;
  while ((m = re.exec(s)) !== null) {
    const name = m[1];
    let i = m.index + m[0].length;
    let depth = 1;
    let stmtStart = i;
    while (i < s.length && depth > 0) {
      const ch = s[i];
      if (ch === '{') depth++;
      else if (ch === '}') {
        depth--;
        if (depth === 0) {
          const tail = s.slice(stmtStart, i).trim();
          const noAcc = tail.replace(/\{\s*(?:get|set)\s*;\s*(?:get|set)?\s*;?\s*\}/g, 'PROP');
          if (/\{/.test(noAcc) && /^(?:void|bool|int|uint|long|float|double|string|event|System\.|Action|Task)\b/.test(noAcc)) {
            issues.push(`${name}: 成员疑似带实现体 → ${noAcc.slice(0, 60)}`);
          }
          if (/^(?:void|bool|int|uint|long|float|double|string|event|System\.|Action|Task)\b[^;{}]*\)\s*$/.test(noAcc.trim())) {
            issues.push(`${name}: 成员缺分号 → ${noAcc.trim().slice(0, 60)}`);
          }
          break;
        }
      } else if (ch === ';' && depth === 1) stmtStart = i + 1;
      i++;
    }
  }
  return issues;
}

const csFiles = [];
(function walk(dir) {
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, e.name);
    if (e.isDirectory()) walk(p);
    else if (e.name.endsWith('.cs')) csFiles.push(p);
  }
})(SCRIPTS);

const asmdefRefs = {};
for (const m of fs.readdirSync(SCRIPTS)) {
  const dir = path.join(SCRIPTS, m);
  if (!fs.statSync(dir).isDirectory()) continue;
  const ad = fs.readdirSync(dir).find((f) => f.endsWith('.asmdef'));
  if (!ad) continue;
  const j = JSON.parse(fs.readFileSync(path.join(dir, ad), 'utf8'));
  asmdefRefs[m] = new Set((j.references ?? []).map((r) => String(r.name ?? r)));
}

let totalLines = 0;
for (const f of csFiles) {
  const rel = path.relative(UNITY, f);
  const raw = fs.readFileSync(f, 'utf8');
  totalLines += raw.split('\n').length;
  const s = strip(raw);

  for (const [open, close, label] of [['{', '}', '花括号'], ['(', ')', '圆括号'], ['[', ']', '方括号']]) {
    const a = (s.match(new RegExp('\\' + open, 'g')) ?? []).length;
    const b = (s.match(new RegExp('\\' + close, 'g')) ?? []).length;
    if (a !== b) P(`${rel}: ${label}不配平（${a} vs ${b}）`);
  }
  if (!/^\s*namespace\s+[\w.]+/m.test(s)) P(`${rel}: 缺 namespace`);
  if ((s.match(/namespace\s+[\w.]+\s*\{/g) ?? []).length === 0) P(`${rel}: namespace 未用花括号形式`);
  for (const issue of interfaceIssues(s)) P(`${rel}: ${issue}`);
  if (/DesignTokens\.cs$/.test(rel) && !raw.startsWith('// <auto-generated>')) P(`${rel}: 生成物缺 <auto-generated> 标记`);

  if (/\/(Gameplay|Net|Audio|Backend)\//.test('/' + rel)) {
    const nc = s.match(/\b(?:const|static\s+readonly)\s+(?:float|double|int)\s+(\w+)\s*=\s*[-\d.]/);
    if (nc) notes.push(`${rel}: 数值常量 ${nc[1]} —— 确认非配置表数值（V9 §19.5）`);
  }

  const mod = rel.split('/')[2];
  if (asmdefRefs[mod]) {
    for (const u of usingsOf(s)) {
      // 只有本仓库自己的命名空间需要 asmdef 引用；System.* / UnityEngine.* 等框架命名空间默认可用
      if (!u.startsWith('Whisper.')) continue;
      const root = u.split('.').slice(0, 2).join('.');
      if (root === `Whisper.${mod}`) continue;
      if (!asmdefRefs[mod].has(root)) P(`${rel}: using ${u}，但 ${mod} 的 asmdef 未引用 ${root}（会编译失败）`);
    }
  }
}

{
  const boot = path.join(SCRIPTS, 'Runtime/GameBootstrap.cs');
  if (fs.existsSync(boot)) {
    const m = fs.readFileSync(boot, 'utf8').match(/LevelResourcePath\s*=\s*"([^"]+)"/);
    if (m) {
      const p = path.join(UNITY, 'Assets/Resources', m[1] + '.json');
      if (!fs.existsSync(p)) P(`GameBootstrap 默认关卡路径 Resources/${m[1]}.json 不存在`);
      else notes.push(`GameBootstrap 默认关卡路径已核实存在：Assets/Resources/${m[1]}.json`);
    }
  }
}

console.log(`[cs-lint] 扫描 ${csFiles.length} 个 .cs（${totalLines} 行）`);
console.log('[cs-lint] 覆盖：括号配平 / namespace 闭合 / interface 成员分号 / 生成物标记 / using↔asmdef / 资源路径');
console.log('[cs-lint] 不覆盖：类型正确性、方法解析、API 存在性、完整编译错误');
for (const n of notes) console.log('  ⚠ ' + n);
if (problems.length) {
  console.log(`结果：${problems.length} 个问题 ✗`);
  for (const p of problems) console.log('  ✗ ' + p);
  process.exit(1);
}
console.log('结果：静态一致性检查通过 ✓');
